#!/usr/bin/env node
// src/cli.ts
// SpecSpec CLI - validate targets against spec files

import path from 'node:path';
import fs from 'node:fs';
import { SpecEngine } from './engine.js';

const args = process.argv.slice(2);

// Help message
const help = `
SpecSpec - Validate targets against spec files

Usage:
  specspec <spec-file> <target-path>
  specspec --init [name]

Commands:
  --init [name]    Create a sample spec file (default: spec.js)
  --help, -h       Show this help message
  --version, -v    Show version

Examples:
  specspec package.spec.js ./my-project
  specspec --init
  specspec --init my-package.spec.js
`;

// Version
function showVersion() {
  const pkgPath = path.resolve(import.meta.dirname, '../package.json');
  const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf-8'));
  console.log(pkg.version);
}

// Init template
const specTemplate = `// Spec file generated by SpecSpec
// Usage: specspec <this-file> <target-path>

// Reusable field definitions
const NameField = Field({ key: 'name', value: Str({ minLength: 1 }) });
const VersionField = Field({ key: 'version', value: Str({ match: /^\\d+\\.\\d+\\.\\d+/ }) });

// Root spec - validates target directory
Directory({
  content: {
    required: [
      JsonFile({
        path: 'package.json',
        required: [NameField, VersionField],
        optional: [
          Field({ key: 'description', value: Str(), optional: true }),
          Field({ key: 'main', value: Str(), optional: true }),
          Field({ key: 'license', value: OneOf('MIT', 'Apache-2.0', 'ISC', Str()), optional: true })
        ]
      })
    ],
    optional: [
      File({ path: 'README.md' }),
      File({ path: 'LICENSE' }),
      Directory({ path: 'src' }),
      Directory({ path: 'test' })
    ]
  }
})
`;

function init(name: string = 'spec.js') {
  const filePath = path.resolve(process.cwd(), name);
  if (fs.existsSync(filePath)) {
    console.error(`Error: File already exists: ${filePath}`);
    process.exit(1);
  }
  fs.writeFileSync(filePath, specTemplate);
  console.log(`Created: ${filePath}`);
  console.log(`\nRun validation with:`);
  console.log(`  specspec ${name} <target-path>`);
}

function validate(specFile: string, targetPath: string) {
  const specPath = path.resolve(process.cwd(), specFile);
  const target = path.resolve(process.cwd(), targetPath);

  // Check spec file exists
  if (!fs.existsSync(specPath)) {
    console.error(`Error: Spec file not found: ${specPath}`);
    process.exit(1);
  }

  // Check target exists
  if (!fs.existsSync(target)) {
    console.error(`Error: Target not found: ${target}`);
    process.exit(1);
  }

  console.log(`Spec:   ${specPath}`);
  console.log(`Target: ${target}`);
  console.log('');

  const engine = new SpecEngine();
  const result = engine.run(specPath, target);

  if (result.ok) {
    console.log('\x1b[32m✓ Validation passed\x1b[0m');
    process.exit(0);
  } else {
    console.log('\x1b[31m✗ Validation failed\x1b[0m\n');
    for (const issue of result.issues) {
      const levelColor = issue.level === 'error' ? '\x1b[31m' : '\x1b[33m';
      const pathStr = issue.path.length > 0 ? issue.path.join('.') : '(root)';
      console.log(`${levelColor}[${issue.level}]\x1b[0m ${issue.code}`);
      console.log(`  ${issue.message}`);
      console.log(`  at: ${pathStr}\n`);
    }
    process.exit(1);
  }
}

// Parse arguments
if (args.length === 0 || args.includes('--help') || args.includes('-h')) {
  console.log(help);
  process.exit(0);
}

if (args.includes('--version') || args.includes('-v')) {
  showVersion();
  process.exit(0);
}

if (args[0] === '--init') {
  init(args[1]);
  process.exit(0);
}

if (args.length < 2) {
  console.error('Error: Missing arguments');
  console.log(help);
  process.exit(1);
}

validate(args[0]!, args[1]!);
